#!/usr/bin/python
# Written by: James Luther
# https://github.com/jaluther/pyMenu

import os,time,copy
import yaml,json

DEBUG = False
DEVICES_FILE = 'inventory.yml'
OLD_SSH_MODELS = ['screenos']

def loadDevices(option):
  if option == 'file':
    with open(DEVICES_FILE, 'r') as stream:
      full_device_dict = yaml.safe_load(stream)
    full_device_list = sorted(full_device_dict.keys())
    return full_device_dict,full_device_list
  if option == 'db':
    print('not implemented yet')

def getUserID(option):
  if option == 'linux':
    return os.getenv('USER')
  if option == 'prompt':
    return raw_input("Username: >> ")

def PrintMenu(menu_list, show_quit=True):
  # clear screen
  os.system('clear')
  # Print header
  print('#'*30)
  print('# SSH Menu')
  print('#'*30)
  # created numbered list (increment to start at 1)
  for i in menu_list:
    print('%s\t%s' % (menu_list.index(i)+1, i))
  # print trailer
  if show_quit:
    print('')
    print('q\tBack')

def ParseChoice(choice):
  choice_list = choice.split(' ')
  choice_num = choice_list[0]
  # prepare vars (decrement by 1 to match dict keys)
  choice_num = int(choice_num)
  choice_num -=1
  # if input below 0 skip loop (raise) - list behavour undesirable
  if choice_num < 0:
    raise Exception('number out of range')
  choice_dict = {'number': choice_num}
  if len(choice_list) > 1:
    choice_dict['id'] = choice_list[1]
  if DEBUG:
    print(choice_dict)
  return choice_dict

def BuildConn(device_list,choice_dict):
  # build out connection string i.e. username@ip/hostname
  choice = choice_dict['number']
  chosen_device = device_list[choice]
  # determine user id
  if 'id' in choice_dict:
    uid = choice_dict['id']
  else:
    uid = defaultid
  # determine if old ciphers should be used
  protocol = 'ssh'
  if 'model' in full_device_dict[chosen_device]:
    if full_device_dict[chosen_device]['model'] in OLD_SSH_MODELS:
      protocol = 'ssh -oHostKeyAlgorithms=+ssh-dss -c 3des-cbc'
  conn = '%s %s@%s' % (protocol, uid, full_device_dict[chosen_device]['ip'])
  return conn

def queryDevList(query_list,device_dict):
  # recursively filter results with multiple query terms
  qlist = copy.deepcopy(query_list)
  if len(qlist) == 0:
    filtered_dev_list = []
    for k,v in device_dict.items():
      filtered_dev_list.append(k)
    return filtered_dev_list
  else:
    filtered_dev_dict = {}
    q = qlist.pop()
    for k,v in device_dict.items():
      if q.lower() in k.lower():
        filtered_dev_dict[k] = v
      if 'vendor' in v:
        if q.lower() == v['vendor'].lower():
          filtered_dev_dict[k] = v
      if 'model' in v:
        if q.lower() == v['model'].lower():
          filtered_dev_dict[k] = v
    return queryDevList(qlist,filtered_dev_dict)

def SearchMenu():
  while True:
    PrintMenu([], show_quit=False)
    # get chosen input
    query = raw_input("Search Query >> ")
    try:
      # If 'q' exit while loop (return)
      if query.lower() == 'q':
        return

      query_list = query.split(' ')

      # Search for matches
      filtered_dev_list = queryDevList(query_list,full_device_dict)

      # remove duplicates and sort list
      filtered_dev_list = list(dict.fromkeys(filtered_dev_list))
      filtered_dev_list.sort()

      # if list isn't empty, create menu
      if filtered_dev_list == []:
        print('!!!! No matching devices found !!!!')
        pause = raw_input('Any key to continue >> ')
      else:
        DeviceListMenu(filtered_dev_list)

    except Exception as e:
      if DEBUG:
        print('Exception caught: %s' % e)
      pass
    if DEBUG:
      time.sleep(1)

def DeviceListMenu(device_list):
  while True:
    PrintMenu(device_list)
    # get chosen input
    choice = raw_input(">> ")
    try:
      # If 'q' exit while loop (return)
      if choice.lower() == 'q':
        return
      choice_dict = ParseChoice(choice)

      # SSH to chosen device
      conn = BuildConn(device_list,choice_dict)
      print("CONNECT: '%s'" % (conn))
      os.system(conn)
    except Exception as e:
      if DEBUG:
        print('Exception caught: %s' % e)
      pass
    if DEBUG:
      time.sleep(1)

if __name__ == "__main__":
  PrintMenu([], show_quit=False)
  defaultid = getUserID('prompt')
  full_device_dict,full_device_list = loadDevices('file')
  SearchMenu()

